INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Montréal', 30000, 'Centre Bell');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Ontario', 30000, 'Ontario Hall');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Vancouver', 30000, 'Vancouver Mega-Center');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('New York', 60000, 'The World');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Washington', 40000, 'Capitol');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('San Fransisco', 40000, 'The Heaven');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Montréal', 30000, 'Centre Bell');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Paris', 60000, 'Zenith');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Berlin', 50000, 'Berghain');
INSERT INTO show_salle (adresse, nb_place, NAME) VALUES ('Mouscou', 30000, 'Opera');