INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('This summer Canada is on fire with one of the best singers. Christopher Owens will ensure different concerts be in several palces : Montreal, Toronto, Quebec City and others', 'img_cw_spec', 'CHRISTOPHER OWENS','Tournée Canada 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('Even USA is his native contrey, Christpher would be glad to sing for the american people. You are waiting for this event ? your waiting will no more lasting. Here he come!', 'img_cw_spec', 'CHRISTOPHER OWENS','Tournée USA 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('Christopher ensure concerts in europe every year since mroe than 5 years. This year will not be an exception. Are you living in Europe ? are you searching for some Fun ? Here he come! dont miss up the event', 'img_cw_spec', 'CHRISTOPHER OWENS','Tournée Europe 2013');

INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('Originaly form Canada, the Royal City group are glad to announce their several Concerts for this summer. Lot of surprises are waiting for you!', 'img_jr_spec', 'JOSH RITTER & THE ROYAL CITY BAND','Tournée Canada 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The group will be in the united states for more than 2 weeks : in NewYork, LasVegas, Miami and more..', 'img_jr_spec', 'JOSH RITTER & THE ROYAL CITY BAND','Tournée USA 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('One of the best rock group will come till you this summer to get out yoour stress. Are you ready ? yes you are !', 'img_jr_spec', 'JOSH RITTER & THE ROYAL CITY BAND','Tournée Europe 2013');

INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The Omar Rodriguez Lopez Group had planned more than 5 shows to expose allover the contrey. It is a good opportunity to live your dream.', 'img_orlg_spec', 'OMAR RODRIGUEZ LOPEZ GROUP','Tournée Canada 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The USA will be up-side down this year with the arrival of one of the best rock group : The Omar Rodriguez Lopez Group. Dont miss it up.', 'img_orlg_spec', 'OMAR RODRIGUEZ LOPEZ GROUP','Tournée USA 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('You live in Europe ? We have a good news! Great opportunity for you this summer ! The Omar Rodriguez Lopez Group is coming to rock your days. Dont miss it up!', 'img_orlg_spec', 'OMAR RODRIGUEZ LOPEZ GROUP','Tournée Europe 2013');

INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('You wanna revive you dreams ?we have the solution : The revivals are coming till you this summer! Dont miss it up!', 'img_r_spec', 'REVIVAL','Tournée Canada 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The REVIVAL wil be in the USA. Keep it secret and if you don''t the places will disappears in one hour. It is not a surprise. it is The rivival', 'img_r_spec', 'REVIVAL','Tournée USA 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('the Rivival are in Europe this summer. Great event for a great continent', 'img_r_spec', 'REVIVAL','Tournée Europe 2013');

INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The Maccabeea are coming to show you rock in the indian way. you will be surprised! dont miss this event!', 'img_tm_spec', 'THE MACCABEES','Tournée Canada 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('It would be a great event with the coming of the The Maccabees group. be there to see a new way to how to rock your life.', 'img_tm_spec', 'THE MACCABEES','Tournée USA 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('Europe knows The Maccabees and the Maccabees Europe. The rule would have an exception this summer! dont miss the event!', 'img_tm_spec', 'THE MACCABEES','Tournée Europe 2013');

INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The group will sing for Canada. WAKEY!WAKEY! for All. dont miss it up!', 'img_ww_spec', 'WAKEY!WAKEY!','Tournée Canada 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('The united states rocks. Obama would dance for their coming. It isnt a surprise, it is the WAKEY!WAKEY! group', 'img_ww_spec', 'WAKEY!WAKEY!','Tournée USA 2013');
INSERT INTO show_spectacle(description, lien_image, artiste_nom, nom_spectacle) VALUES ('You live in Europe ? We have a good news! Great opportunity for you this summer ! The WAKEY!WAKEY! are coming. Dont miss it up!', 'img_ww_spec', 'WAKEY!WAKEY!','Tournée Europe 2013');